### ISSUE TITLE
大佬OpenWrt可以安装adguard吗?可以出个教程吗?

### ISSUE THREAD

**Issue by 02107** [happyzhang1995/luci-app-adguardhome#1]

**Comment by happyzhang1995** [comment]
待会上传-------- 原始邮件 --------发件人： 02107 <notifications@github.com>日期： 2019年10月7日周一 17:54收件人： happyzhang1995/luci-app-adguardhome <luci-app-adguardhome@noreply.github.com>抄送： Subscribed <subscribed@noreply.github.com>主    题： [happyzhang1995/luci-app-adguardhome] 大佬OpenWrt可以安装adguard吗?可以出个教程吗? (#1)

**Comment by happyzhang1995** [comment]
更新了readme，你看一下吧里面有对应的adhome的链接，拷到package里面编译就行了

**Comment by 02107** [comment]
谢谢.

**Comment by xman55555** [comment]
大佬，不会编译啊。。怎么弄？
