### ISSUE TITLE
请问一下加的两个依赖是用于做什么的

### ISSUE THREAD

**Issue by adamw92** [happyzhang1995/luci-app-adguardhome#3]
请问一下，加入的两个依赖iputils-arping和curl是用来做什么的，adguardhome并不需要额外安装依赖，luci里似乎也没有相关的调用。

**Comment by happyzhang1995** [comment]
不好意思，上传的是之前还没完工的，我也是照着其他luci依葫芦画瓢改的，那是之前的luci依赖，现已修改为ADguardhome
