### ISSUE TITLE
openwrt 没有systemd无法网页配置adguard

### ISSUE THREAD

**Issue by rufengsuixing** [happyzhang1995/luci-app-adguardhome#4]
日志如下
root@newifi-d1-home:/etc#  /usr/bin/AdGuardHome/AdGuardHome -v
2019/11/20 15:16:21 [error] Couldn't read config file /usr/bin/AdGuardHome/AdGua                                                                                                             rdHome.yaml: open /usr/bin/AdGuardHome/AdGuardHome.yaml: no such file or directo                                                                                                             ry
2019/11/20 15:16:21 31024#1 [info] AdGuard Home, version v0.99.2, channel releas                                                                                                             e

2019/11/20 15:16:21 31024#1 [debug] Current working directory is /usr/bin/AdGuar                                                                                                             dHome
2019/11/20 15:16:21 31024#1 [info] This is the first launch of AdGuard Home, red                                                                                                             irecting everything to /install.html
2019/11/20 15:16:21 31024#1 [info] AdGuard Home is available on the following ad                                                                                                             dresses:
2019/11/20 15:16:21 31024#12 [debug] github.com/AdguardTeam/AdGuardHome/home.(*c                                                                                                             lientsContainer).AddHost(): '127.0.0.1' -> 'localhost' [1]
2019/11/20 15:16:21 31024#12 [debug] github.com/AdguardTeam/AdGuardHome/home.(*c                                                                                                             lientsContainer).AddHost(): '::1' -> 'localhost' [2]
2019/11/20 15:16:21 31024#12 [debug] github.com/AdguardTeam/AdGuardHome/home.(*c                                                                                                             lientsContainer).AddHost(): 'ff02::1' -> 'ip6-allnodes' [3]
2019/11/20 15:16:21 31024#12 [debug] github.com/AdguardTeam/AdGuardHome/home.(*c                                                                                                             lientsContainer).AddHost(): 'ff02::2' -> 'ip6-allrouters' [4]
2019/11/20 15:16:21 31024#12 [debug] Added 4 client aliases from /etc/hosts
2019/11/20 15:16:21 31024#12 [debug] github.com/AdguardTeam/AdGuardHome/home.(*c                                                                                                             lientsContainer).addFromSystemARP(): executing arp [arp -a]
2019/11/20 15:16:21 31024#12 [debug] command arp has failed: exec: "arp": execut                                                                                                             able file not found in $PATH code:-1
2019/11/20 15:16:21 31024#12 [debug] Added 0 client aliases from DHCP
2019/11/20 15:16:21 31024#1 [info] Go to http://127.0.0.1:3000
2019/11/20 15:16:21 31024#1 [info] Go to http://192.168.0.1:3000
2019/11/20 15:16:21 31024#1 [info] Go to http://192.168.192.55:3000
2019/11/20 15:16:34 31024#33 [debug] GET /control/install/get_addresses
2019/11/20 15:16:36 31024#33 [debug] POST /control/install/check_config
2019/11/20 15:16:36 31024#33 [debug] github.com/AdguardTeam/AdGuardHome/home.che                                                                                                             ckDNSStubListener(): executing systemctl [systemctl is-enabled systemd-resolved]
2019/11/20 15:16:36 31024#33 [error] command systemctl has failed: exec: "system                                                                                                             ctl": executable file not found in $PATH code:-1
2019/11/20 15:16:38 31024#33 [debug] POST /control/install/check_config
2019/11/20 15:16:38 31024#33 [debug] github.com/AdguardTeam/AdGuardHome/home.che                                                                                                             ckDNSStubListener(): executing systemctl [systemctl is-enabled systemd-resolved]
2019/11/20 15:16:38 31024#33 [error] command systemctl has failed: exec: "system                                                                                                             ctl": executable file not found in $PATH code:-1
2019/11/20 15:16:40 31024#33 [debug] POST /control/install/check_config
2019/11/20 15:16:40 31024#33 [debug] github.com/AdguardTeam/AdGuardHome/home.che                                                                                                             ckDNSStubListener(): executing systemctl [systemctl is-enabled systemd-resolved]
2019/11/20 15:16:40 31024#33 [error] command systemctl has failed: exec: "system                                                                                                             ctl": executable file not found in $PATH code:-1
2019/11/20 15:16:44 31024#33 [debug] POST /control/install/check_config
2019/11/20 15:16:44 31024#33 [debug] github.com/AdguardTeam/AdGuardHome/home.che                                                                                                             ckDNSStubListener(): executing systemctl [systemctl is-enabled systemd-resolved]
2019/11/20 15:16:44 31024#33 [error] command systemctl has failed: exec: "system                                                                                                             ctl": executable file not found in $PATH code:-1
2019/11/20 15:16:46 31024#33 [debug] POST /control/install/check_config
2019/11/20 15:17:01 31024#33 [debug] POST /control/install/configure
2019/11/20 15:17:01 31024#33 [debug] github.com/AdguardTeam/AdGuardHome/stats.(*                                                                                                             statsCtx).dbOpen(): db.Open...
2019/11/20 15:17:01 31024#33 [error] Stats: open DB: /usr/bin/AdGuardHome/data/s                                                                                                             tats.db: invalid argument
2019/11/20 15:17:01 31024#33 [fatal] Couldn't initialize statistics module
root@newifi-d1-home:/etc#

**Comment by rufengsuixing** [comment]
建议给一个临时yaml模板，这样用户可以成功进入，进行网页版的设置

**Comment by rufengsuixing** [comment]
不需要systemd也能启动，问题是stats.db的问题

**Comment by happyzhang1995** [comment]
额，你这问题有点高端。。。我纯小白，这软件是我照着openwrt的官方wiki编的

**Comment by rufengsuixing** [comment]
我自己写了2333333，用我的吧
