### ISSUE TITLE
因为adguard 的bug stats.db对文件系统有要求，无法启动

### ISSUE THREAD

**Issue by rufengsuixing** [happyzhang1995/luci-app-adguardhome#5]
硬路由默认的文件系统
/dev/root on /rom type squashfs (ro,relatime)
tmpfs on /tmp type tmpfs (rw,nosuid,nodev,noatime)
/dev/mtdblock6 on /overlay type jffs2 (rw,noatime)
overlayfs:/overlay on / type overlay (rw,noatime,lowerdir=/,upperdir=/overlay/upper,workdir=/overlay/work)
无法启动，使用`ln -s /tmp/stats.db /usr/bin/AdGuardHome/data/stats.db`可以启动
对于硬路由算是一个暂时解决办法
也已经向官方反馈

**Comment by xiaofami** [comment]
> 硬路由默认的文件系统
> /dev/root on /rom type squashfs (ro,relatime)
> tmpfs on /tmp type tmpfs (rw,nosuid,nodev,noatime)
> /dev/mtdblock6 on /overlay type jffs2 (rw,noatime)
> overlayfs:/overlay on / type overlay (rw,noatime,lowerdir=/,upperdir=/overlay/upper,workdir=/overlay/work)
> 无法启动，使用`ln -s /tmp/stats.db /usr/bin/AdGuardHome/data/stats.db`可以启动
> 对于硬路由算是一个暂时解决办法
> 也已经向官方反馈

我尝试在K3上用这个方法，但是有以下问题：
1.`/tmp/stats.db` 这个文件不存在
2.`/usr/bin/AdGuardHome` 目录下只有这一个文件：
> root@OpenWrt:/usr/bin/AdGuardHome# ls -l
> -rwxr-xr-x    1 root     root      13126088 Dec 14 13:09 AdGuardHome

并不存在`data/`及下面的`stats.db`文件

另外我用的是[coolsnowwolf/lede](https://github.com/coolsnowwolf/lede)源码，给软路由编译的vmdk固件没有问题

**Comment by rufengsuixing** [comment]
我自己写了luci
