### ISSUE TITLE
可以过滤内容吗？还是仅仅通过DNS拦截广告？

### ISSUE THREAD

**Issue by adaaaaaa** [happyzhang1995/luci-app-adguardhome#6]
RT。。。还有个做luci插件的老哥只做DNS拦截。。。不能过滤内容。。。可惜了。。。几乎没有效果。。。

**Comment by happyzhang1995** [comment]
我这个跟他那个一样，adg本来就只能做dns拦截，说实话我也觉得这玩意一点用也没有

**Comment by adaaaaaa** [comment]
> 我也觉得这玩意一点用也没有

那能不能把ublock origin搞个luci插件呢？？电脑端很棒。。。应该是过滤内容的吧？🤪🤪🤪

**Comment by happyzhang1995** [comment]
> > 我也觉得这玩意一点用也没有
> 
> 那能不能把ublock origin搞个luci插件呢？？电脑端很棒。。。应该是过滤内容的吧？🤪🤪🤪

不行这是浏览器插件，里面很多规则都不能通用的，只能在浏览器上实现
